### ISSUE TITLE
Placing bid through CLI fails with error `invalid paying coin denom`

### ISSUE THREAD

**Issue by lumtis** [tendermint/fundraising#126]
## Summary of Bug

Hey
I'm using `fundraising` imported in `spn` and I'm encountering an issue when trying to place a bid for a fixed price auction from the guide https://github.com/tendermint/fundraising/blob/main/docs/How-To/cli/README.md#placebid
Once an auction has been created and a bidder is added. If I follow the command described in the guide, I get

```
spnd tx fundraising bid 1 1.0 1000v/1/orbit --from bob

memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
code: 6
codespace: fundraising
data: ""
events:
- attributes:
  - index: false
    key: ZmVl
    value: ""
  type: tx
- attributes:
  - index: false
    key: YWNjX3NlcQ==
    value: c3BuMWFxbjh5bnZyM2ptcTY3ODc5cXVsenJ3aGNocTVkdHJ2dHgwbmhlLzU=
  type: tx
- attributes:
  - index: false
    key: c2lnbmF0dXJl
    value: WHJSb0lPeS9udnNOTDVDUVlsbnJGVHhscEYreEl5UE56UTZaNDVCYVd3c210UUNtTE5CZ2JCNjRxd2E0ZStISEo5eWp2ZFRpNDQzY3lQa2dIZU1vUXc9PQ==
  type: tx
gas_used: "40445"
gas_wanted: "200000"
height: "977"
info: ""
logs: []
raw_log: 'failed to execute message; message index: 0: invalid paying coin denom'
timestamp: ""
tx: null
txhash: 753F784AD8F1CCE71CCF7B242BF5E9E84582DD50965AADA30EC3D5E1D43C7CE3
```

If I set the denom in the command

```
spnd tx fundraising bid 1 2uspn 1000v/1/orbit --from bob

Error: failed to set decimal string: 2uspn000000000000000000
```

The state of the auction is:
```
auctions:
- '@type': /tendermint.fundraising.FixedPriceAuction
  base_auction:
    allowed_bidders:
    - bidder: spn1aqn8ynvr3jmq67879qulzrwhchq5dtrvtx0nhe
      max_bid_amount: "1000"
    auctioneer: spn1ezptsm3npn54qx9vvpah4nymre59ykr9exx2ul
    end_times:
    - "2022-03-17T17:00:00Z"
    id: "1"
    paying_coin_denom: uspn
    paying_reserve_address: spn17gk7a5ys8pxuexl7tvyk3pc9tdmqjjek03zjemez4eqvqdxlu92q40mw7q
    remaining_coin:
      amount: "50000"
      denom: v/1/orbit
    selling_coin:
      amount: "50000"
      denom: v/1/orbit
    selling_reserve_address: spn1wl90665mfk3pgg095qhmlgha934exjvv437acgq42zw0sg94flesnndv8k
    start_price: "1000.000000000000000000"
    start_time: "2022-03-16T00:00:00Z"
    status: AUCTION_STATUS_STARTED
    type: AUCTION_TYPE_FIXED_PRICE
    vesting_reserve_address: spn1q4x4k4qsr4jwrrugnplhlj52mfd9f8jn5ck7r4ykdpv9wczvz4dqplk6fp
    vesting_schedules: []
    winning_price: "0.000000000000000000"
```

Auction file is
```
{
  "start_price": "1000.0",
  "min_bid_price": "1.0",
  "selling_coin": {
    "denom": "v/1/orbit",
    "amount": "50000"
  },
  "paying_coin_denom": "uspn",
  "vesting_schedules": [],
  "start_time": "2022-03-16T00:00:00Z",
  "end_time": "2022-03-17T17:00:00Z"
}
```

Do you think it would be something wrong with the CLI command?

## Version

`v0.1.1` imported in `spn` https://github.com/tendermint/spn on `develop`

## Steps to Reproduce

```
starport c serve -r (from spn)
spnd tx profile create-coordinator --from alice -y
spnd tx campaign create-campaign orbit 1000000orbit --from alice -y
spnd tx campaign mint-vouchers 1 50000orbit --from alice -y
spnd tx fundraising create-fixed-price-auction auction.json --from alice -y
spnd tx participation participate 1 0 --from bob -y (add allowed bidder)
spnd tx fundraising bid 1 1.0 1000v/1/orbit --from bob -y
```

## Tasks

- 

## References

-
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jaybxyz** [comment]
Thanks for the report. It works well with `fundraisingd`. Let me test with `spnd` now and get back to this.

**Comment by lumtis** [comment]
> Thanks for the report. It works well with `fundraisingd`. Let me test with `spnd` now and get back to this.

Ok, I can investigate if something is wrong with the import of the module

**Comment by jaybxyz** [comment]
@lubtd According to the auction file you provided above, the `start_price` is 1000 and the paying coin denom is `uspn`
It looks like you are placing a bid with incorrect arguments. For `FixedPriceAuction` type, `coin` argument must be the paying coin denom.

```bash
# Usage
spnd tx fundraising bid [auction-id] [price] [coin]

# It must be the following command
# A bidder wants to place a bid with 2uspn worth of selling coin
spnd tx fundraising bid 1 1000 2uspn --from bob
```

**Comment by jaybxyz** [comment]
To give you an update about the recent change(s) while implementing `BatchAuction` type, `bid` CLI command requires one more argument. See [this line of code](https://github.com/tendermint/fundraising/blob/main/x/fundraising/client/cli/tx.go#L251).

And, I just notice that it is missing in our How-to docs. I will update the docs up to date by tomorrow.

**Comment by lumtis** [comment]
Ohh OK I see, this is the total tokens you want to spend for the bid. I thought it was the amount of selling coins you are bidding.

Is there any specific reason for having this interface in the message? In my personal opinion I would have said that providing the amount of selling coins to bid is a more intuitive representation

**Comment by lumtis** [comment]
Closing since the initial object of the issue is now resolved
