### ISSUE TITLE
`MsgModifyBid` missing in the module handler

### ISSUE THREAD

**Issue by lumtis** [tendermint/fundraising#140]
## Summary of Bug

Importing `fundraising` in https://github.com/tendermint/spn, the module doesn't recognize `MsgMofidyBid`
```
spnd tx fundraising modify-bid 1 1 100 15000v/1/orbit --from bob -y
code: 6
codespace: sdk
data: ""
events:
- attributes:
  - index: false
    key: ZmVl
    value: ""
  type: tx
- attributes:
  - index: false
    key: YWNjX3NlcQ==
    value: c3BuMWFxbjh5bnZyM2ptcTY3ODc5cXVsenJ3aGNocTVkdHJ2dHgwbmhlLzc=
  type: tx
- attributes:
  - index: false
    key: c2lnbmF0dXJl
    value: U1czVFQ2cDJXUnVSUnBPSzh4NGhmUno2bGE4a1FJSFBtalY5NDV3UUd2VVoyRU52a2I1V2o2T1JsUmplR2tweUM4bWJyYmVuYW1NZXFmNzU3NWFwWlE9PQ==
  type: tx
gas_used: "38226"
gas_wanted: "200000"
height: "2697"
info: ""
logs: []
raw_log: 'failed to execute message; message index: 0: unrecognized fundraising message
  type: *types.MsgModifyBid: unknown request'
timestamp: ""
tx: null
txhash: DA71184A236024B2833C3F2730F9B0E5F93654C95C50F0C05D44A1F1837CBF2C
```
Looking into the module it seems that the handler is missing an entry to handle `MsgModifyBid: `https://github.com/tendermint/fundraising/blob/0863b616db9caef56c0763398287d7f05e116e1d/x/fundraising/handler.go#L16

## Version

Last commit in `develop`: 0863b616db9caef56c0763398287d7f05e116e1d

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by lumtis** [comment]
Also maybe it's because the branch is under development

Tell me if we should stick to the previous release for now

**Comment by jaybxyz** [comment]
@lubtd Thanks for the report. Yes, i see it is missing an entry in handler. I will go fix it today. In regards of the next version, we are planning to release next version sometime next week. Right now, we are targeting next Tuesday. We will give you an update when it is released.

**Comment by lumtis** [comment]
Ok perfect, thanks 👍

Should we wait for the release before doing any experimentation with Batch Auctions?

**Comment by jaybxyz** [comment]
The following stuff is basically what we have left until the next release. As you see, they are mostly implementing tests to discover if there is any bug in codebase. The core logic implementation is already implemented. So, if you are willing to experiment `BatchAuction`, I think you can go experiment it from the latest `main` branch, and of course you can wait for a couple more days for a little more stable codebase.

- Implement CLI integration tests
- Implement simulation tests
- Write benchmark to see if there is any performance issue when calculating bids for BatchAuction.
