### ISSUE TITLE
Add `AfterFixedPriceAuctionCreated ` and `AfterBatchAuctionCreated` hooks

### ISSUE THREAD

**Issue by lumtis** [tendermint/fundraising#182]
## Summary

Adding `AfterFixedPriceAuctionCreated` and `AfterBatchAuctionCreated` hooks similar to currently implemented `BeforeFixedPriceAuctionCreated ` and `BeforeBatchAuctionCreated` hooks but with `auctionID` value available.

## Problem Definition

Current `BeforeFixedPriceAuctionCreated ` and `BeforeBatchAuctionCreated` hooks don't give access to the `auctionID` since the auction is not yet created at the time the hook is called.
For some specific purpose, the `auctionID` must be accessed.
Example: in `spn` https://github.com/tendermint/spn we wish to access the `auctionID` to associate an auction ID with a related campaign ID when an auction is created.

## Proposal

Add `AfterFixedPriceAuctionCreated ` and `AfterBatchAuctionCreated` hooks similar to `BeforeFixedPriceAuctionCreated ` and `BeforeBatchAuctionCreated`  but that includes the auction ID

## Tasks

- 

## References

-
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jaybxyz** [comment]
@lubtd Sure, we will add those requested `After` hooks.
