### ISSUE TITLE
feat: add Batch auction core logic

### ISSUE THREAD

**Issue by jaybxyz** [tendermint/fundraising#43]
## Summary

This issue requests to add core logics for [AuctionBatchType](https://github.com/tendermint/fundraising/blob/main/x/fundraising/spec/01_concepts.md#english-auction) following the technical spec design.

## Tasks

- Add necessary keeper logics for Batch auction
- Add command line interface
- Update endblocker 
- Update spec docs if there is any change

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jaybxyz** [comment]
Moved the note from #50. 

> One thing to note is that we need to handle an exception for Extended (a number of extended rounds) value when implementing English auction in #43. The release time for vesting schedule must be properly handled depending on the value of Extended. Otherwise, the auction can be extended for x number of rounds and some vesting schedules may already have finished.

**Comment by kogisin** [comment]
This issue can be broken down into several issues.

**Comment by jaybxyz** [comment]
This issue is broken down into serveral issues. I will close this once everything is organized and settled.
