### ISSUE TITLE
deps: spm package is moving to starport/pkg

### ISSUE THREAD

**Issue by jaybxyz** [tendermint/fundraising#66]
## Summary

The fundraising module uses Starport modules called [spm](https://github.com/tendermint/spm), and now Starport team is working to move them under [starport/pkg](https://github.com/tendermint/starport/tree/develop/starport/pkg). We need to check if the module needs to do anything with it. See this https://github.com/tendermint/starport/pull/1968 for reference.

## Tasks

- Check if the module needs to do anything other than changing the import path to `starport/pkg`

## References

- https://github.com/tendermint/spm
- https://github.com/tendermint/starport/tree/develop/starport/pkg
- See this https://github.com/tendermint/starport/pull/1968
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ilgooz** [comment]
This change will be introduced with [v0.19.2](https://github.com/tendermint/starport/milestone/14) release.
